# Generated by Django 4.2.7 on 2025-11-15 05:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('allocations', models.JSONField(default=dict, help_text='Budget allocations by category: {category: {percentage: float, amount: float}}')),
                ('allocation_method', models.CharField(choices=[('smart', 'Smart Allocation'), ('manual', 'Manual Allocation')], default='smart', max_length=20)),
                ('efficiency_score', models.FloatField(default=85.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('cost_per_guest', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost_per_hour', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('insights', models.JSONField(default=dict, help_text='Budget insights and recommendations')),
                ('detailed_breakdown', models.JSONField(default=dict, help_text='Detailed breakdown with requirement mappings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Untitled Event', max_length=255)),
                ('event_type', models.CharField(choices=[('corporate', 'Corporate'), ('wedding', 'Wedding'), ('birthday', 'Birthday'), ('festival', 'Festival'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('attendees', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('venue_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('hybrid', 'Hybrid')], default='indoor', max_length=20)),
                ('duration', models.PositiveIntegerField(default=4, help_text='Duration in hours', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('total_budget', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('services', models.JSONField(default=list, help_text='List of selected services')),
                ('form_data', models.JSONField(default=dict)),
                ('special_requirements', models.JSONField(blank=True, default=dict, help_text='Format: {req_id: {selected: bool, quantity: int, unit: str, questions: list, answers: dict}}')),
                ('selected_services', models.JSONField(blank=True, default=list, help_text='List of selected service names')),
                ('created_by', models.CharField(blank=True, help_text='Name of the user who created the event', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('image_url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_images',
            },
        ),
        migrations.CreateModel(
            name='EventMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestones', models.JSONField(default=dict, help_text='Milestone completion data in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_milestones',
            },
        ),
        migrations.CreateModel(
            name='EventRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=200)),
                ('requirement_id', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_requirements',
            },
        ),
        migrations.CreateModel(
            name='EventRequirementImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('requirement_name', models.CharField(max_length=100)),
                ('image_number', models.IntegerField()),
                ('image_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_requirement_images',
                'ordering': ['event_name', 'requirement_name', 'image_number'],
            },
        ),
        migrations.CreateModel(
            name='EventSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_sections',
            },
        ),
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hero_videos',
            },
        ),
        migrations.CreateModel(
            name='TraditionStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('style_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'events_traditionstyle',
            },
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('vendors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendor_categories',
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_data', models.JSONField(default=dict, help_text='Complete guest information in JSON format')),
                ('invitation_code', models.CharField(db_index=True, help_text='Unique invitation code for guest', max_length=50, unique=True)),
                ('response_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('maybe', 'Maybe')], db_index=True, default='pending', max_length=20)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('plus_ones', models.IntegerField(default=0, help_text='Number of additional guests', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Special dietary requirements')),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests from guest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_rsvps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(blank=True, help_text='Readable requirement name for easy identification', max_length=200)),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, help_text='Options for dropdown/radio/checkbox', null=True)),
                ('placeholder', models.CharField(blank=True, max_length=100)),
                ('min_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_questions', to='events.eventrequirement')),
            ],
            options={
                'db_table': 'requirement_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_name', models.CharField(blank=True, max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('guest_count', models.PositiveIntegerField(default=0)),
                ('budget_range', models.CharField(blank=True, max_length=50)),
                ('services', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('quote_type', models.CharField(choices=[('targeted', 'Targeted'), ('comprehensive', 'Comprehensive')], default='comprehensive', max_length=20)),
                ('expand_vendors', models.BooleanField(default=False, help_text='Include additional vendors beyond selected ones')),
                ('is_targeted_quote', models.BooleanField(default=False)),
                ('prefilled_event_id', models.PositiveIntegerField(blank=True, help_text='ID of the event this quote is based on', null=True)),
                ('selected_vendors', models.JSONField(default=list, help_text='List of specifically selected vendors')),
                ('selected_venues', models.JSONField(default=list, help_text='List of specifically selected venues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quote_requests',
            },
        ),
        migrations.CreateModel(
            name='EventSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='events.eventsection')),
            ],
            options={
                'db_table': 'event_subsections',
            },
        ),
        migrations.AddConstraint(
            model_name='eventsection',
            constraint=models.UniqueConstraint(fields=('section_id',), name='unique_section_id'),
        ),
        migrations.AddIndex(
            model_name='eventrequirement',
            index=models.Index(fields=['event_id'], name='event_requi_event_i_a78a31_idx'),
        ),
        migrations.AddField(
            model_name='eventmilestone',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones_data', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='eventimage',
            index=models.Index(fields=['event_id'], name='event_image_event_i_ae77f2_idx'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='events.event'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['event', 'response_status'], name='event_rsvps_event_i_cf344e_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['user', 'response_status'], name='event_rsvps_user_id_a57247_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['invitation_code'], name='event_rsvps_invitat_603337_idx'),
        ),
        migrations.AddConstraint(
            model_name='rsvp',
            constraint=models.UniqueConstraint(fields=('event', 'invitation_code'), name='unique_invitation_per_event'),
        ),
        migrations.AddConstraint(
            model_name='rsvp',
            constraint=models.CheckConstraint(check=models.Q(('plus_ones__gte', 0)), name='non_negative_plus_ones'),
        ),
        migrations.AddIndex(
            model_name='requirementquestion',
            index=models.Index(fields=['requirement', 'order'], name='requirement_require_de9c78_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirementquestion',
            constraint=models.CheckConstraint(check=models.Q(('min_value__isnull', True), ('max_value__isnull', True), ('min_value__lt', models.F('max_value')), _connector='OR'), name='min_value_less_than_max_value'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['user'], name='quote_reque_user_id_7f720e_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['status'], name='quote_reque_status_9d808a_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['created_at'], name='quote_reque_created_016cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsubsection',
            index=models.Index(fields=['subsection_id'], name='event_subse_subsect_a7f44a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsubsection',
            index=models.Index(fields=['section', 'subsection_id'], name='event_subse_section_5826b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventsubsection',
            constraint=models.UniqueConstraint(fields=('section', 'subsection_id'), name='unique_subsection_per_section'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'created_at'], name='events_user_id_3ca773_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'created_at'], name='events_event_t_9f6b23_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('attendees__gte', 1)), name='positive_attendees'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('total_budget__gt', 0)), name='positive_budget'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(check=models.Q(('total_budget__gt', 0)), name='positive_total_budget'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(check=models.Q(('efficiency_score__gte', 0), ('efficiency_score__lte', 100)), name='valid_efficiency_score'),
        ),
    ]
