# Generated by Django 4.2.7 on 2025-11-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('vendors_notified', 'Vendors Notified'), ('responses_received', 'Responses Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
