# Generated by Django 4.2.7 on 2025-11-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_category_specific_data'),
        ('events', '0004_add_vendor_responses'),
    ]

    operations = [
    ]
