# Generated by Django 4.2.7 on 2025-11-19 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_merge_20251118_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.TextField(blank=True)),
                ('includes', models.JSONField(default=list, help_text="What's included in this quote")),
                ('excludes', models.JSONField(default=list, help_text="What's not included")),
                ('terms', models.TextField(blank=True, help_text='Terms and conditions')),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendor_quotes',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='budget',
            name='allocation_method',
            field=models.CharField(choices=[('smart', 'Smart'), ('manual', 'Manual')], default='smart', max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='allocations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='budget',
            name='cost_per_guest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='cost_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='detailed_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='budget',
            name='efficiency_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='insights',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.CharField(blank=True, default='', help_text='Name or identifier of event creator', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventmilestone',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventmilestone',
            name='milestones',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='budget_range',
            field=models.CharField(default='50000-100000', max_length=50),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='category_specific_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='client_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='event_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='event_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='expand_vendors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='guest_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='prefilled_event_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='quote_type',
            field=models.CharField(choices=[('comprehensive', 'Comprehensive'), ('targeted', 'Targeted')], default='comprehensive', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='selected_vendors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='selected_venues',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='source_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('vendors_notified', 'Vendors Notified'), ('responses_received', 'Responses Received'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='urgency',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='vendor_responses',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='dietary_restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='guest_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='invitation_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='plus_ones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='response_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('maybe', 'Maybe')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorquote',
            name='quote_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_quote', to='events.quoterequest'),
        ),
        migrations.AddIndex(
            model_name='vendorquote',
            index=models.Index(fields=['status'], name='vendor_quot_status_e17605_idx'),
        ),
    ]
