# Generated by Django 4.2.7 on 2025-11-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_vendorquote_alter_event_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorQuote',
        ),
    ]
