# Generated by Django 4.2.7 on 2025-11-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_vendorquote_quote_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='source_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
