# Generated by Django 4.2.7 on 2025-11-17 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('action_url_template', models.CharField(blank=True, max_length=500)),
                ('variables', models.JSONField(default=dict, help_text='Available template variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_in_app', models.BooleanField(default=True)),
                ('quote_notifications', models.BooleanField(default=True)),
                ('booking_notifications', models.BooleanField(default=True)),
                ('payment_notifications', models.BooleanField(default=True)),
                ('message_notifications', models.BooleanField(default=True)),
                ('marketing_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_start_time', models.TimeField(default='22:00')),
                ('quiet_end_time', models.TimeField(default='08:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('quote_received', 'Quote Received'), ('quote_accepted', 'Quote Accepted'), ('quote_rejected', 'Quote Rejected'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('payment_due', 'Payment Due'), ('payment_overdue', 'Payment Overdue'), ('event_reminder', 'Event Reminder'), ('vendor_assigned', 'Vendor Assigned'), ('event_completed', 'Event Completed'), ('new_message', 'New Message'), ('vendor_portfolio', 'Vendor Portfolio'), ('vendor_availability', 'Vendor Availability'), ('account_verified', 'Account Verified'), ('password_changed', 'Password Changed'), ('vendor_recommendation', 'Vendor Recommendation'), ('new_quote_request', 'New Quote Request'), ('profile_viewed', 'Profile Viewed'), ('seasonal_alert', 'Seasonal Alert'), ('price_suggestion', 'Price Suggestion'), ('new_booking', 'New Booking'), ('payment_received', 'Payment Received'), ('customer_cancelled', 'Customer Cancelled'), ('review_received', 'Review Received'), ('customer_message', 'Customer Message'), ('quote_response', 'Quote Response'), ('event_changes', 'Event Changes'), ('rsvp_update', 'RSVP Update'), ('performance_summary', 'Performance Summary'), ('revenue_milestone', 'Revenue Milestone'), ('profile_views_up', 'Profile Views Increased'), ('system_maintenance', 'System Maintenance'), ('security_alert', 'Security Alert'), ('platform_update', 'Platform Update'), ('promotion', 'Promotion'), ('referral_reward', 'Referral Reward'), ('loyalty_reward', 'Loyalty Reward'), ('event_tips', 'Event Tips'), ('trend_alert', 'Trend Alert')], max_length=50)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx')],
            },
        ),
    ]
