# Generated by Django 4.2.7 on 2025-11-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorauth_remove_vendorprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorauth',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
