# Generated by Django 4.2.7 on 2025-11-17 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0004_vendorauth_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorauth',
            name='chat_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
