# Generated by Django 4.2.7 on 2025-11-17 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorauth_chat_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorServicePackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_people', models.IntegerField(blank=True, null=True)),
                ('maximum_people', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to='vendors.vendorauth')),
            ],
            options={
                'db_table': 'vendor_service_packages',
            },
        ),
    ]
