# Generated by Django 4.2.7 on 2025-11-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_is_active_message_message_type_and_more'),
    ]

    operations = [
    ]
