# Generated by Django 4.2.7 on 2025-11-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20251115_1541'),
        ('chat', '0003_production_chat'),
    ]

    operations = [
    ]
