# Generated by Django 4.2.7 on 2025-11-17 03:49

import app.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_enhanced_chat_features'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_vendor__60b925_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_custome_522d68_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_vendor__6f7cff_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_is_acti_098e7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_3154fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_sender__b02346_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_78be40_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_4d8903_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_fe668e_idx',
            old_name='chat_message_conv_status_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_message_973666_idx',
            old_name='chat_message_msg_type_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(upload_to=app.chat.models.upload_path),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='chat_conver_last_me_31163c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['vendor', '-last_message_at'], name='chat_conver_vendor__423da4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['customer', '-last_message_at'], name='chat_conver_custome_c55eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='chat_messag_convers_d0740f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_id'], name='chat_messag_message_1cb7fe_idx'),
        ),
    ]
